let veriable_alien = 'green'
//if block run
if (veriable_alien==='green'){
    console.log('player just earned 5 points for shooting the alien.')
}
else{
    console.log("the player just earned 10 points.")
}



veriable_alien = 'red'
//else block run
if (veriable_alien==='green'){
    console.log('player just earned 5 points for shooting the alien.')
}
else{
    console.log("the player just earned 10 points.")}

