let car = 'subaru';

//5 true tests

//equality test
console.log("is car == 'subaru' ? i predict true.")
console.log(car == 'subaru'); //true





//stric equality test
console.log("is car === 'subaru' ? i predict true.")
console.log(car === 'subaru'); //true



//inequality test
console.log("is car != 'toyota' ? i predict true.")
console.log(car != 'toyota'); //true



//istric inequality test
console.log("is car !== 'toyota' ? i predict true.")
console.log(car !== 'toyota'); //true




//equality test
console.log("is car == 'subaru' ? i predict true.")
console.log(car == 'subaru'); //true


//5 false test



//equality test
console.log("is car == 'undifine' ? i predict true.")
console.log(car == 'undifine'); //false




//stric equality test
console.log("is car === 'toyota' ? i predict true.")
console.log(car === 'toyota'); //false


//stric equality test
console.log("is car === 'null' ? i predict true.")
console.log(car === 'null'); //false

//inequality test
console.log("is car != 'subaru' ? i predict true.")
console.log(car != 'subaru'); //false
